hosts:
  - 192.168.201.150
  - 192.168.201.151
  - 192.168.201.152

keyspace: test2
query: select * from test
# Should be idempotent
schemaCommands:
  - "CREATE KEYSPACE IF NOT EXISTS test2 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3 }"
  - "CREATE TABLE IF NOT EXISTS test2.test ( id int PRIMARY KEY , value text )"

reconnectionInterval: 1000
socketReadTimeout: 500
socketTimeout: 500

# Logging settings.
logging:
  level: INFO
  loggers:
    "com.datastax.driver": OFF

server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 9179
      outputBufferSize: 32KiB
      idleTimeout: 30 seconds
      minBufferPoolSize: 64 bytes
      bufferPoolIncrement: 1KiB
      maxBufferPoolSize: 64KiB
      acceptorThreads: 1
      selectorThreads: 2
      acceptQueueSize: 1024
      reuseAddress: true
      soLingerTime: 600s
  adminConnectors:
    - type: http
      port: 9180

metrics:
  reporters:
    - type: graphite
      host: 192.168.10.120
      port: 2003
      prefix: cassandra-health
      durationUnit: milliseconds
      rateUnit: seconds
      frequency: 1 second

graphiteHost: 192.168.10.120