hosts:
  - 127.0.0.1
  - 127.0.0.2
  - 127.0.0.3

keyspace: test2
#query: select * from test
query: select * from test where id = 1
# Should be idempotent
schemaCommands:
  - "CREATE KEYSPACE IF NOT EXISTS test2 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3 }"
  - "CREATE TABLE IF NOT EXISTS test2.test ( id int PRIMARY KEY , value text )"

reconnectionInterval: 1000
socketReadTimeout: 500
socketTimeout: 500

# Logging settings.
logging:
  level: INFO
  loggers:
    "com.datastax.driver": INFO
  appenders:
    - type: console
      logFormat: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


server:
  rootPath: /api/*

metrics:
  reporters:
    - type: graphite
      host: 192.168.10.120
      port: 2003
      prefix: cassandra-health
      durationUnit: milliseconds
      rateUnit: seconds
      frequency: 1 second

graphiteHost: 192.168.10.120